WEB_DIRECTORY = "./js"

# Sick Ollie Classic: frozen at the dev25 interaction model and original node IDs.
from .loader_core import NODE_CLASS_MAPPINGS as CLASSIC_LOADER_CLASSES, NODE_DISPLAY_NAME_MAPPINGS as CLASSIC_LOADER_NAMES
from .prompt_core import NODE_CLASS_MAPPINGS as CLASSIC_PROMPT_CLASSES, NODE_DISPLAY_NAME_MAPPINGS as CLASSIC_PROMPT_NAMES
from .generation_core import NODE_CLASS_MAPPINGS as CLASSIC_GENERATION_CLASSES, NODE_DISPLAY_NAME_MAPPINGS as CLASSIC_GENERATION_NAMES
from .output_core import NODE_CLASS_MAPPINGS as CLASSIC_OUTPUT_CLASSES, NODE_DISPLAY_NAME_MAPPINGS as CLASSIC_OUTPUT_NAMES
from .preview_core import NODE_CLASS_MAPPINGS as CLASSIC_PREVIEW_CLASSES, NODE_DISPLAY_NAME_MAPPINGS as CLASSIC_PREVIEW_NAMES
from .persistent_resolved_prompt import NODE_CLASS_MAPPINGS as CLASSIC_PERSIST_CLASSES, NODE_DISPLAY_NAME_MAPPINGS as CLASSIC_PERSIST_NAMES
from .metadata_core import NODE_CLASS_MAPPINGS as CLASSIC_METADATA_CLASSES, NODE_DISPLAY_NAME_MAPPINGS as CLASSIC_METADATA_NAMES

# Sick Ollie Studio: redesigned dashboard generation with independent node IDs.
from .studio_loader_core import NODE_CLASS_MAPPINGS as STUDIO_LOADER_CLASSES, NODE_DISPLAY_NAME_MAPPINGS as STUDIO_LOADER_NAMES
from .studio_prompt_core import NODE_CLASS_MAPPINGS as STUDIO_PROMPT_CLASSES, NODE_DISPLAY_NAME_MAPPINGS as STUDIO_PROMPT_NAMES
from .studio_generation_core import NODE_CLASS_MAPPINGS as STUDIO_GENERATION_CLASSES, NODE_DISPLAY_NAME_MAPPINGS as STUDIO_GENERATION_NAMES
from .studio_output_core import NODE_CLASS_MAPPINGS as STUDIO_OUTPUT_CLASSES, NODE_DISPLAY_NAME_MAPPINGS as STUDIO_OUTPUT_NAMES
from .studio_preview_core import NODE_CLASS_MAPPINGS as STUDIO_PREVIEW_CLASSES, NODE_DISPLAY_NAME_MAPPINGS as STUDIO_PREVIEW_NAMES
from .studio_persistent_resolved_prompt import NODE_CLASS_MAPPINGS as STUDIO_PERSIST_CLASSES, NODE_DISPLAY_NAME_MAPPINGS as STUDIO_PERSIST_NAMES
from .studio_metadata_core import NODE_CLASS_MAPPINGS as STUDIO_METADATA_CLASSES, NODE_DISPLAY_NAME_MAPPINGS as STUDIO_METADATA_NAMES

NODE_CLASS_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS = {}

for mapping in (
    CLASSIC_LOADER_CLASSES, CLASSIC_PROMPT_CLASSES, CLASSIC_GENERATION_CLASSES,
    CLASSIC_OUTPUT_CLASSES, CLASSIC_PREVIEW_CLASSES, CLASSIC_PERSIST_CLASSES, CLASSIC_METADATA_CLASSES,
    STUDIO_LOADER_CLASSES, STUDIO_PROMPT_CLASSES, STUDIO_GENERATION_CLASSES,
    STUDIO_OUTPUT_CLASSES, STUDIO_PREVIEW_CLASSES, STUDIO_PERSIST_CLASSES, STUDIO_METADATA_CLASSES,
):
    NODE_CLASS_MAPPINGS.update(mapping)

for mapping in (
    CLASSIC_LOADER_NAMES, CLASSIC_PROMPT_NAMES, CLASSIC_GENERATION_NAMES,
    CLASSIC_OUTPUT_NAMES, CLASSIC_PREVIEW_NAMES, CLASSIC_PERSIST_NAMES, CLASSIC_METADATA_NAMES,
    STUDIO_LOADER_NAMES, STUDIO_PROMPT_NAMES, STUDIO_GENERATION_NAMES,
    STUDIO_OUTPUT_NAMES, STUDIO_PREVIEW_NAMES, STUDIO_PERSIST_NAMES, STUDIO_METADATA_NAMES,
):
    NODE_DISPLAY_NAME_MAPPINGS.update(mapping)

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
