WEB_DIRECTORY = "./js"

from .loader_core import NODE_CLASS_MAPPINGS as LOADER_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as LOADER_DISPLAY_NAME_MAPPINGS
from .prompt_core import NODE_CLASS_MAPPINGS as PROMPT_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as PROMPT_DISPLAY_NAME_MAPPINGS
from .generation_core import NODE_CLASS_MAPPINGS as GENERATION_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as GENERATION_DISPLAY_NAME_MAPPINGS
from .output_core import NODE_CLASS_MAPPINGS as OUTPUT_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as OUTPUT_DISPLAY_NAME_MAPPINGS
from .preview_core import NODE_CLASS_MAPPINGS as PREVIEW_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as PREVIEW_DISPLAY_NAME_MAPPINGS
from .persistent_resolved_prompt import NODE_CLASS_MAPPINGS as PERSISTENT_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as PERSISTENT_DISPLAY_NAME_MAPPINGS

NODE_CLASS_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS = {}

for mapping in (
    LOADER_CLASS_MAPPINGS,
    PROMPT_CLASS_MAPPINGS,
    GENERATION_CLASS_MAPPINGS,
    OUTPUT_CLASS_MAPPINGS,
    PREVIEW_CLASS_MAPPINGS,
    PERSISTENT_CLASS_MAPPINGS,
):
    NODE_CLASS_MAPPINGS.update(mapping)

for mapping in (
    LOADER_DISPLAY_NAME_MAPPINGS,
    PROMPT_DISPLAY_NAME_MAPPINGS,
    GENERATION_DISPLAY_NAME_MAPPINGS,
    OUTPUT_DISPLAY_NAME_MAPPINGS,
    PREVIEW_DISPLAY_NAME_MAPPINGS,
    PERSISTENT_DISPLAY_NAME_MAPPINGS,
):
    NODE_DISPLAY_NAME_MAPPINGS.update(mapping)

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
